#!/usr/bin/env python3
"""
Workflow Demo - Research to Linear Issue
Demonstrates multi-step MCP-powered workflows.
"""
from __future__ import annotations

import asyncio
from datetime import datetime, timezone


# ---------------------------------------------------------------------------
# Workflow 1: Research → Linear Issue
# ---------------------------------------------------------------------------

async def workflow_research_to_linear(topic: str, team_id: str) -> dict:
    """
    Research a topic with Perplexity then create a Linear issue.

    Steps:
    1. Search for information using Perplexity
    2. Create Linear issue with research summary
    """
    print(f"\n{'=' * 70}")
    print("WORKFLOW: Research → Linear Issue")
    print(f"{'=' * 70}")
    print(f"Topic: {topic}")
    print(f"Team:  {team_id}")
    print(f"Started: {datetime.now(tz=timezone.utc).isoformat()}\n")

    # Step 1: Research
    print("🔍 Step 1: Researching with Perplexity…")
    content = ""
    citations: list[str] = []
    try:
        from perplexity_ask import perplexity_ask  # type: ignore[import-not-found]

        research = perplexity_ask(
            messages=[
                {"role": "system", "content": "You are a research assistant. Provide comprehensive information."},
                {"role": "user", "content": f"Research: {topic}. Provide key findings, best practices, and implementation tips."},
            ],
            search_context_size="high",
        )

        if isinstance(research, dict):
            content = research.get("content", "")
            citations = research.get("citations", [])
        else:
            content = str(research)

        print(f"  ✅ Research complete ({len(content)} chars)")
        print(f"  📚 Citations: {len(citations)}")
    except Exception as exc:
        print(f"  ❌ Research failed: {exc}")
        content = f"Research on: {topic}\n\n[Error during research: {exc}]"

    # Step 2: Create Linear issue
    print("\n📝 Step 2: Creating Linear issue…")
    try:
        from linear_createIssue import linear_createIssue  # type: ignore[import-not-found]

        truncated = content[:2000] + ("…" if len(content) > 2000 else "")
        citation_lines = (
            "\n".join(f"- {c}" for c in citations[:5]) if citations else "- Research-based findings"
        )
        now_iso = datetime.now(tz=timezone.utc).isoformat()

        issue = linear_createIssue(
            title=f"Research: {topic}",
            description=(
                f"## Research Summary\n\n"
                f"**Topic:** {topic}\n"
                f"**Date:** {now_iso}\n\n"
                f"### Findings\n\n{truncated}\n\n"
                f"### Citations\n\n{citation_lines}\n\n"
                f"---\n*Generated by Kimi MCP Client workflow*\n"
            ),
            teamId=team_id,
            priority=3,
        )

        print(f"  ✅ Issue created: {issue.get('identifier', 'N/A')}")
        print(f"  🔗 URL: {issue.get('url', 'N/A')}")

        return {
            "success": True,
            "issue": issue,
            "research_summary": content[:500],
            "citations_count": len(citations),
        }

    except Exception as exc:
        print(f"  ❌ Failed to create issue: {exc}")
        return {
            "success": False,
            "error": str(exc),
            "research_summary": content[:500],
        }


# ---------------------------------------------------------------------------
# Workflow 2: Bug Fix
# ---------------------------------------------------------------------------

async def workflow_bug_fix(issue_id: str, repo: str) -> dict:
    """
    Gather context for fixing a Linear bug report.

    Steps:
    1. Retrieve Linear issue details
    2. Search GitHub for related code
    """
    print(f"\n{'=' * 70}")
    print("WORKFLOW: Bug Fix")
    print(f"{'=' * 70}")
    print(f"Issue: {issue_id}")
    print(f"Repo:  {repo}")
    print(f"Started: {datetime.now(tz=timezone.utc).isoformat()}\n")

    # Step 1: Get issue details
    print("📋 Step 1: Getting issue details…")
    title = "Unknown"
    try:
        from linear_getIssueById import linear_getIssueById  # type: ignore[import-not-found]

        issue = linear_getIssueById(id=issue_id)
        title = issue.get("title", "Unknown")
        print(f"  ✅ Issue: {title}")
    except Exception as exc:
        print(f"  ❌ Failed: {exc}")
        return {"success": False, "error": str(exc)}

    # Step 2: Search code
    print("\n🔍 Step 2: Searching code…")
    items: list = []
    try:
        from search_code import search_code  # type: ignore[import-not-found]

        keywords = " ".join(title.split()[:3])
        results = search_code(q=f"{keywords} repo:{repo}")
        items = results.get("items", [])
        print(f"  ✅ Found {len(items)} code matches")
    except Exception as exc:
        print(f"  ❌ Search failed: {exc}")

    # Step 3: Placeholder — manual code changes required
    print("\n📦 Step 3: Creating fix PR…")
    print("  ⏸️  Skipped — requires manual code changes")

    return {
        "success": True,
        "issue": {"title": title, "id": issue_id},
        "code_matches": len(items),
        "note": "Manual code changes required",
    }


# ---------------------------------------------------------------------------
# Workflow 3: Competitive Analysis
# ---------------------------------------------------------------------------

async def workflow_competitive_analysis(query: str, team_id: str) -> dict:
    """
    Run a competitive analysis and file results as a Linear issue.

    Steps:
    1. Brave web search for competitors
    2. Perplexity deep-dive analysis
    3. Create Linear issue with findings
    """
    print(f"\n{'=' * 70}")
    print("WORKFLOW: Competitive Analysis")
    print(f"{'=' * 70}")
    print(f"Query: {query}")
    print(f"Started: {datetime.now(tz=timezone.utc).isoformat()}\n")

    # Step 1: Web search
    print("🦁 Step 1: Searching competitors…")
    web_results: list = []
    try:
        from brave_web_search import brave_web_search  # type: ignore[import-not-found]

        search_results = brave_web_search(query=f"{query} competitors alternatives 2024")
        web_results = search_results.get("web", {}).get("results", [])
        print(f"  ✅ Found {len(web_results)} results")
    except Exception as exc:
        print(f"  ❌ Search failed: {exc}")

    # Step 2: Deep research
    print("\n🔍 Step 2: Deep research…")
    analysis = f"Analysis of {query}"
    try:
        from perplexity_research import perplexity_research  # type: ignore[import-not-found]

        research = perplexity_research(
            messages=[
                {
                    "role": "user",
                    "content": (
                        f"Comprehensive competitive analysis of {query}. "
                        "Include market leaders, pricing, strengths/weaknesses, and market trends."
                    ),
                }
            ],
            reasoning_effort="high",
        )
        analysis = research.get("content", str(research))[:3000]
        print("  ✅ Analysis complete")
    except Exception as exc:
        print(f"  ❌ Research failed: {exc}")

    # Step 3: Create issue
    print("\n📝 Step 3: Creating Linear issue…")
    competitor_lines = (
        "\n".join(f"- {r.get('title', 'N/A')}: {r.get('url', '')}" for r in web_results[:5])
        if web_results
        else "- Research in progress"
    )
    now_iso = datetime.now(tz=timezone.utc).isoformat()

    try:
        from linear_createIssue import linear_createIssue  # type: ignore[import-not-found]

        issue = linear_createIssue(
            title=f"Competitive Analysis: {query}",
            description=(
                f"## Competitive Analysis: {query}\n\n"
                f"**Date:** {now_iso}\n\n"
                f"### Key Competitors\n\n{competitor_lines}\n\n"
                f"### Analysis\n\n{analysis}\n\n"
                f"---\n*Generated by Kimi MCP Client*\n"
            ),
            teamId=team_id,
            priority=2,
        )

        print(f"  ✅ Issue created: {issue.get('identifier')}")
        return {
            "success": True,
            "issue": issue,
            "competitors_found": len(web_results),
        }
    except Exception as exc:
        print(f"  ❌ Failed: {exc}")
        return {"success": False, "error": str(exc)}


# ---------------------------------------------------------------------------
# Demo runner
# ---------------------------------------------------------------------------

async def main() -> None:
    """Run all workflow demos."""
    print("\n" + "=" * 70)
    print("KIMI MCP CLIENT - WORKFLOW DEMOS")
    print("=" * 70)

    result1 = await workflow_research_to_linear(
        topic="React Server Components best practices",
        team_id="2d851660-3f0d-4be2-9555-dcbaf55bf8fa",
    )

    result2 = await workflow_bug_fix(
        issue_id="KIM-1",
        repo="Nietzsche-Ubermensch/kimi-cli-tools",
    )

    result3 = await workflow_competitive_analysis(
        query="AI coding assistants",
        team_id="2d851660-3f0d-4be2-9555-dcbaf55bf8fa",
    )

    print("\n" + "=" * 70)
    print("WORKFLOW SUMMARY")
    print("=" * 70)
    print(f"Research → Linear:   {'✅' if result1.get('success') else '❌'}")
    print(f"Bug Fix:             {'✅' if result2.get('success') else '❌'}")
    print(f"Competitive Analysis:{'✅' if result3.get('success') else '❌'}")
    print("\n✅ All workflows demonstrated!")


if __name__ == "__main__":
    asyncio.run(main())
