#!/usr/bin/env python3
"""
Workflow Demo - Research to Linear Issue
Demonstrates the research_to_linear workflow
"""

import asyncio
from datetime import datetime

async def workflow_research_to_linear(topic: str, team_id: str):
    """
    Workflow: Research a topic with Perplexity → Create Linear issue
    
    Steps:
    1. Search for information using Perplexity
    2. Summarize findings
    3. Create Linear issue with research summary
    """
    print(f"\n{'='*70}")
    print(f"WORKFLOW: Research → Linear Issue")
    print(f"{'='*70}")
    print(f"Topic: {topic}")
    print(f"Team: {team_id}")
    print(f"Started: {datetime.now().isoformat()}\n")
    
    # Step 1: Research
    print("🔍 Step 1: Researching with Perplexity...")
    try:
        from perplexity_ask import perplexity_ask
        
        research = perplexity_ask(
            messages=[
                {"role": "system", "content": "You are a research assistant. Provide comprehensive information."},
                {"role": "user", "content": f"Research: {topic}. Provide key findings, best practices, and implementation tips."}
            ],
            search_context_size="high"
        )
        
        if isinstance(research, dict):
            content = research.get("content", "")
            citations = research.get("citations", [])
        else:
            content = str(research)
            citations = []
        
        print(f"  ✅ Research complete ({len(content)} chars)")
        print(f"  📚 Citations: {len(citations)}")
    except Exception as e:
        print(f"  ❌ Research failed: {e}")
        content = f"Research on: {topic}\n\n[Error during research: {e}]"
        citations = []
    
    # Step 2: Create Linear issue
    print("\n📝 Step 2: Creating Linear issue...")
    try:
        from linear_createIssue import linear_createIssue
        
        issue_title = f"Research: {topic}"
        issue_description = f"""## Research Summary

**Topic:** {topic}
**Date:** {datetime.now().isoformat()}

### Findings

{content[:2000]}{'...' if len(content) > 2000 else ''}

### Citations

{chr(10).join(f'- {c}' for c in citations[:5]) if citations else '- Research-based findings'}

---
*Generated by Kimi MCP Client workflow*
"""
        
        issue = linear_createIssue(
            title=issue_title,
            description=issue_description,
            teamId=team_id,
            priority=3
        )
        
        print(f"  ✅ Issue created: {issue.get('identifier', 'N/A')}")
        print(f"  🔗 URL: {issue.get('url', 'N/A')}")
        
        return {
            "success": True,
            "issue": issue,
            "research_summary": content[:500],
            "citations_count": len(citations)
        }
    
    except Exception as e:
        print(f"  ❌ Failed to create issue: {e}")
        return {
            "success": False,
            "error": str(e),
            "research_summary": content[:500]
        }


async def workflow_bug_fix(issue_id: str, repo: str):
    """
    Workflow: Fix bug from Linear issue
    
    Steps:
    1. Get Linear issue details
    2. Search GitHub code for related files
    3. Create fix PR
    4. Update Linear issue with PR link
    """
    print(f"\n{'='*70}")
    print(f"WORKFLOW: Bug Fix")
    print(f"{'='*70}")
    print(f"Issue: {issue_id}")
    print(f"Repo: {repo}")
    print(f"Started: {datetime.now().isoformat()}\n")
    
    # Step 1: Get issue details
    print("📋 Step 1: Getting issue details...")
    try:
        from linear_getIssueById import linear_getIssueById
        issue = linear_getIssueById(id=issue_id)
        title = issue.get("title", "Unknown")
        description = issue.get("description", "")
        print(f"  ✅ Issue: {title}")
    except Exception as e:
        print(f"  ❌ Failed: {e}")
        return {"success": False, "error": str(e)}
    
    # Step 2: Search code
    print("\n🔍 Step 2: Searching code...")
    try:
        from search_code import search_code
        
        # Extract keywords from title
        keywords = " ".join(title.split()[:3])
        results = search_code(
            q=f"{keywords} repo:{repo}"
        )
        
        items = results.get("items", [])
        print(f"  ✅ Found {len(items)} code matches")
    except Exception as e:
        print(f"  ❌ Search failed: {e}")
        items = []
    
    # Step 3: Create placeholder PR
    print("\n📦 Step 3: Creating fix PR...")
    print(f"  ⏸️  (Skipped - requires manual code changes)")
    
    return {
        "success": True,
        "issue": {"title": title, "id": issue_id},
        "code_matches": len(items),
        "note": "Manual code changes required"
    }


async def workflow_competitive_analysis(query: str, team_id: str):
    """
    Workflow: Competitive analysis → Linear issue
    
    Steps:
    1. Brave search for competitors
    2. Perplexity deep research
    3. Create Linear issue with analysis
    """
    print(f"\n{'='*70}")
    print(f"WORKFLOW: Competitive Analysis")
    print(f"{'='*70}")
    print(f"Query: {query}")
    print(f"Started: {datetime.now().isoformat()}\n")
    
    # Step 1: Web search
    print("🦁 Step 1: Searching competitors...")
    try:
        from brave_web_search import brave_web_search
        
        search_results = brave_web_search(query=f"{query} competitors alternatives 2024")
        web_results = search_results.get("web", {}).get("results", [])
        print(f"  ✅ Found {len(web_results)} results")
    except Exception as e:
        print(f"  ❌ Search failed: {e}")
        web_results = []
    
    # Step 2: Deep research
    print("\n🔍 Step 2: Deep research...")
    try:
        from perplexity_research import perplexity_research
        
        research = perplexity_research(
            messages=[
                {"role": "user", "content": f"Comprehensive competitive analysis of {query}. Include market leaders, pricing, strengths/weaknesses, and market trends."}
            ],
            reasoning_effort="high"
        )
        
        analysis = research.get("content", str(research))[:3000]
        print(f"  ✅ Analysis complete")
    except Exception as e:
        print(f"  ❌ Research failed: {e}")
        analysis = f"Analysis of {query}"
    
    # Step 3: Create issue
    print("\n📝 Step 3: Creating Linear issue...")
    try:
        from linear_createIssue import linear_createIssue
        
        issue = linear_createIssue(
            title=f"Competitive Analysis: {query}",
            description=f"""## Competitive Analysis: {query}

**Date:** {datetime.now().isoformat()}

### Key Competitors

{chr(10).join(f"- {r.get('title', 'N/A')}: {r.get('url', '')}" for r in web_results[:5]) if web_results else "- Research in progress"}

### Analysis

{analysis}

---
*Generated by Kimi MCP Client*
""",
            teamId=team_id,
            priority=2
        )
        
        print(f"  ✅ Issue created: {issue.get('identifier')}")
        return {
            "success": True,
            "issue": issue,
            "competitors_found": len(web_results)
        }
    except Exception as e:
        print(f"  ❌ Failed: {e}")
        return {"success": False, "error": str(e)}


async def main():
    """Run all workflow demos."""
    print("\n" + "="*70)
    print("KIMI MCP CLIENT - WORKFLOW DEMOS")
    print("="*70)
    
    # Workflow 1: Research to Linear
    result1 = await workflow_research_to_linear(
        topic="React Server Components best practices",
        team_id="2d851660-3f0d-4be2-9555-dcbaf55bf8fa"
    )
    
    # Workflow 2: Bug fix
    result2 = await workflow_bug_fix(
        issue_id="KIM-1",
        repo="Nietzsche-Ubermensch/kimi-cli-tools"
    )
    
    # Workflow 3: Competitive analysis
    result3 = await workflow_competitive_analysis(
        query="AI coding assistants",
        team_id="2d851660-3f0d-4be2-9555-dcbaf55bf8fa"
    )
    
    # Summary
    print("\n" + "="*70)
    print("WORKFLOW SUMMARY")
    print("="*70)
    print(f"Research → Linear: {'✅' if result1.get('success') else '❌'}")
    print(f"Bug Fix: {'✅' if result2.get('success') else '❌'}")
    print(f"Competitive Analysis: {'✅' if result3.get('success') else '❌'}")
    
    print("\n✅ All workflows demonstrated!")


if __name__ == "__main__":
    asyncio.run(main())
